Dsm-DAS/DAS_BACKEND

.github/CODEOWNERS
=> 🔀 :: (#1) CODEOWNERS 세팅

build.gradle
=> 🔀 :: (#5) 파일 구조 세팅

src/main/java/com/das/das_backend/domain/user/domain/User.java, src/main/java/com/das/das_backend/infrastructure/s3/DefaultImage.java
=> 🔀 :: (#7) User 엔티티 생성

src/main/java/com/das/das_backend/domain/user/domain/User.java, src/main/java/com/das/das_backend/global/enums/Authority.java
=> 🔀 :: (#10) 권한 컬럼 추가

src/main/java/com/das/das_backend/domain/feed/domain/Feed.java, src/main/java/com/das/das_backend/domain/user/domain/User.java
=> 🔀 :: (#12) Feed 엔티티 생성

src/main/java/com/das/das_backend/domain/comment/domain/Comment.java, src/main/java/com/das/das_backend/global/entity/BaseTimeEntity.java
=> 🔀 :: (#14) Comment 엔티티 생성

src/main/java/com/das/das_backend/domain/like/domain/Like.java
=> 🔀 :: (#16) like 엔티티 생성

src/main/java/com/das/das_backend/domain/comment/domain/Comment.java, src/main/java/com/das/das_backend/domain/feed/domain/Feed.java, src/main/java/com/das/das_backend/domain/user/domain/User.java, src/main/java/com/das/das_backend/global/entity/BaseIdEntity.java, src/main/java/com/das/das_backend/global/entity/BaseTimeIdEntity.java
=> 🔀 :: (#18) 엔티티 기본키 버그 수정

src/main/java/com/das/das_backend/domain/notice/Notice.java
=> 🔀 :: (#20) Notice 엔티티 생성

src/main/java/com/das/das_backend/global/error/DasException.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java, src/main/java/com/das/das_backend/global/error/ErrorResponse.java, src/main/java/com/das/das_backend/global/error/ExceptionFilter.java, src/main/java/com/das/das_backend/global/error/GlobalExceptionHandler.java
=> 🔀 :: (#22) 예외처리 추가

src/main/java/com/das/das_backend/domain/user/domain/repository/UserRepository.java, src/main/java/com/das/das_backend/domain/user/exception/UserNotFoundException.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java, src/main/java/com/das/das_backend/global/security/SecurityConfig.java, src/main/java/com/das/das_backend/global/security/auth/AuthDetails.java, src/main/java/com/das/das_backend/global/security/auth/AuthDetailsService.java
=> 🔀 :: (#24) security setting

src/main/java/com/das/das_backend/DasBackendApplication.java, src/main/java/com/das/das_backend/domain/auth/domain/RefreshToken.java, src/main/java/com/das/das_backend/domain/auth/domain/repository/RefreshTokenRepository.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java, src/main/java/com/das/das_backend/global/exception/ExpiredTokenException.java, src/main/java/com/das/das_backend/global/exception/InvalidTokenException.java, src/main/java/com/das/das_backend/global/redis/RedisConfig.java, src/main/java/com/das/das_backend/global/security/jwt/JwtProperties.java, src/main/java/com/das/das_backend/global/security/jwt/JwtTokenFilter.java, src/main/java/com/das/das_backend/global/security/jwt/JwtTokenProvider.java
=> 🔀 :: (#26) jwt setting

src/main/java/com/das/das_backend/domain/refresh_token/domain/RefreshToken.java, src/main/java/com/das/das_backend/domain/refresh_token/domain/repository/RefreshTokenRepository.java, src/main/java/com/das/das_backend/domain/user/exception/PasswordMisMatchException.java, src/main/java/com/das/das_backend/domain/user/presentation/UserController.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/request/UserSignInRequest.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/response/TokenResponse.java, src/main/java/com/das/das_backend/domain/user/service/UserSignInService.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java, src/main/java/com/das/das_backend/global/security/jwt/JwtTokenProvider.java
=> 🔀 :: (#29) 로그인 api

src/main/java/com/das/das_backend/domain/user/exception/UserAlreadyExistsException.java, src/main/java/com/das/das_backend/domain/user/presentation/UserController.java, src/main/java/com/das/das_backend/domain/user/presentation/UserController2.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/request/UserSignUpRequest.java, src/main/java/com/das/das_backend/domain/user/service/UserSignUpService.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java, src/main/java/com/das/das_backend/global/security/SecurityConfig.java, src/main/java/com/das/das_backend/infrastructure/s3/DefaultImage.java
=> 🔀 :: (#28) 유저 회원가입 api

src/main/java/com/das/das_backend/domain/refresh_token/domain/RefreshToken.java, src/main/java/com/das/das_backend/domain/user/domain/User.java, src/main/java/com/das/das_backend/domain/user/domain/repository/UserRepository.java, src/main/java/com/das/das_backend/domain/user/facade/UserFacade.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/request/UserSignInRequest.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/request/UserSignUpRequest.java, src/main/java/com/das/das_backend/domain/user/service/UserSignInService.java, src/main/java/com/das/das_backend/domain/user/service/UserSignUpService.java, src/main/java/com/das/das_backend/global/security/SecurityConfig.java
=> 🔀 :: (#35) accountId + email -> email로 수정

src/main/java/com/das/das_backend/domain/user/presentation/UserController.java, src/main/java/com/das/das_backend/domain/user/service/UserWithdrawalService.java, src/main/java/com/das/das_backend/global/security/SecurityConfig.java
=> 🔀:: (#38) 회원탈퇴 api

src/main/java/com/das/das_backend/domain/user/domain/User.java, src/main/java/com/das/das_backend/domain/user/presentation/UserController.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/request/ChangePasswordRequest.java, src/main/java/com/das/das_backend/domain/user/service/ChangePasswordService.java
=> 🔀 :: (#39) 비밀번호 수정 API

src/main/java/com/das/das_backend/domain/feed/domain/repository/FeedRepository.java, src/main/java/com/das/das_backend/domain/feed/presentation/FeedController.java, src/main/java/com/das/das_backend/domain/feed/presentation/dto/request/CreateFeedRequest.java, src/main/java/com/das/das_backend/domain/feed/service/CreateFeedService.java
=> 🔀 :: (#44) 모집글 작성 API

src/main/java/com/das/das_backend/domain/like/domain/Like.java, src/main/java/com/das/das_backend/domain/refresh_token/domain/RefreshToken.java, src/main/java/com/das/das_backend/domain/refresh_token/domain/repository/RefreshTokenRepository.java, src/main/java/com/das/das_backend/domain/user/exception/InvalidRefreshTokenException.java, src/main/java/com/das/das_backend/domain/user/presentation/UserController.java, src/main/java/com/das/das_backend/domain/user/service/TokenRefreshService.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java, src/main/java/com/das/das_backend/global/security/auth/AuthDetails.java, src/main/java/com/das/das_backend/global/security/auth/AuthDetailsService.java, src/main/java/com/das/das_backend/global/security/jwt/JwtTokenProvider.java
=> 🔀 :: (#41) 토큰 재발급 API

src/main/java/com/das/das_backend/domain/feed/domain/Feed.java, src/main/java/com/das/das_backend/domain/feed/exception/FeedCannotUpdateException.java, src/main/java/com/das/das_backend/domain/feed/exception/FeedNotFoundException.java, src/main/java/com/das/das_backend/domain/feed/facade/FeedFacade.java, src/main/java/com/das/das_backend/domain/feed/presentation/FeedController.java, src/main/java/com/das/das_backend/domain/feed/presentation/dto/request/UpdateFeedRequest.java, src/main/java/com/das/das_backend/domain/feed/service/UpdateFeedService.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java
=> 🔀 :: (#47) 모집글 수정 API

src/main/java/com/das/das_backend/domain/notice/domain/Notice.java, src/main/java/com/das/das_backend/domain/notice/domain/repository/NoticeRepository.java, src/main/java/com/das/das_backend/domain/notice/presentation/NoticeController.java, src/main/java/com/das/das_backend/domain/notice/presentation/dto/request/CreateNoticeRequest.java, src/main/java/com/das/das_backend/domain/notice/service/CreateNoticeService.java, src/main/java/com/das/das_backend/global/security/SecurityConfig.java
=> 🔀 :: (#48) 공지 사항 작성 API

src/main/java/com/das/das_backend/domain/feed/exception/FeedCannotDeleteException.java, src/main/java/com/das/das_backend/domain/feed/presentation/FeedController.java, src/main/java/com/das/das_backend/domain/feed/service/DeleteFeedService.java, src/main/java/com/das/das_backend/domain/feed/service/UpdateFeedService.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java
=> 🔀 :: (#51) 모집글 삭제 API

src/main/java/com/das/das_backend/domain/comment/service/DeleteCommentService.java
=> 🔀 :: (#58) 댓글 삭제 API

src/main/java/com/das/das_backend/domain/comment/presentation/dto/request/UpdateCommentRequest.java, src/main/java/com/das/das_backend/domain/comment/service/UpdateCommentService.java
=> 🔀 :: (#56) 댓글 수정 API

src/main/java/com/das/das_backend/global/web/WebMvcConfig.java
=> 🔀 :: (#61) CORS 버그

build.gradle, src/main/java/com/das/das_backend/domain/user/domain/AuthCode.java, src/main/java/com/das/das_backend/domain/user/domain/repository/AuthCodeRepository.java, src/main/java/com/das/das_backend/domain/user/exception/InvalidAuthCodeException.java, src/main/java/com/das/das_backend/domain/user/exception/UnVerifiedAuthCodeException.java, src/main/java/com/das/das_backend/domain/user/exception/WrongEmailException.java, src/main/java/com/das/das_backend/domain/user/facade/AuthCodeFacade.java, src/main/java/com/das/das_backend/domain/user/facade/UserFacade.java, src/main/java/com/das/das_backend/domain/user/presentation/UserController.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/request/EmailRequest.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/request/VerifyAuthCodeRequest.java, src/main/java/com/das/das_backend/domain/user/service/AuthCodeService.java, src/main/java/com/das/das_backend/domain/user/service/UserSignUpService.java, src/main/java/com/das/das_backend/domain/user/service/VerifyAuthCodeService.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java, src/main/java/com/das/das_backend/global/security/FilterConfig.java, src/main/java/com/das/das_backend/global/security/SecurityConfig.java, src/main/java/com/das/das_backend/global/util/JmsUtil.java, src/main/resources/application.yml
=> 🔀 :: (#46) Email 인증 API

src/main/java/com/das/das_backend/domain/comment/service/UpdateCommentService.java
=> 🔀 :: (#63) updateCommentService 수정

src/main/java/com/das/das_backend/domain/comment/presentation/CommentController.java, src/main/java/com/das/das_backend/global/security/SecurityConfig.java
=> 🔀 :: (#68) SecurityConfig url 접근 권한 추가

build.gradle, src/main/java/com/das/das_backend/domain/image/presentation/ImageController.java, src/main/java/com/das/das_backend/domain/image/presentation/dto/response/ImageUrlResponse.java, src/main/java/com/das/das_backend/domain/image/service/ImageUploadService.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java, src/main/java/com/das/das_backend/global/exception/ImageValueNotFoundException.java, src/main/java/com/das/das_backend/global/exception/SaveImageFailedException.java, src/main/java/com/das/das_backend/infrastructure/s3/S3Facade.java, src/main/java/com/das/das_backend/infrastructure/s3/S3Properties.java, src/main/resources/application.yml
=> 🔀 :: (#70) S3 setting

build.gradle, src/main/java/com/das/das_backend/DasBackendApplication.java, src/main/java/com/das/das_backend/global/socket/SocketRunner.java, src/main/java/com/das/das_backend/global/socket/WebSocketConfig.java, src/main/java/com/das/das_backend/global/socket/connect/SocketJwtHandler.java, src/main/java/com/das/das_backend/global/socket/exception/SocketExceptionListener.java, src/main/java/com/das/das_backend/global/socket/property/ClientProperty.java, src/main/java/com/das/das_backend/global/socket/property/SocketProperty.java, src/main/resources/application.yml
=> 🔀 :: (#71) 소켓 setting

src/main/java/com/das/das_backend/domain/feed/domain/Feed.java, src/main/java/com/das/das_backend/domain/like/domain/repository/LikeRepository.java, src/main/java/com/das/das_backend/domain/like/exception/LikeExistException.java, src/main/java/com/das/das_backend/domain/like/exception/RemoveLikeExistException.java, src/main/java/com/das/das_backend/domain/like/facade/LikeFacade.java, src/main/java/com/das/das_backend/domain/like/presentation/LikeController.java, src/main/java/com/das/das_backend/domain/like/presentation/dto/response/LikeResponse.java, src/main/java/com/das/das_backend/domain/like/service/LikeService.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java
=> 🔀 :: (#77) 모집글 좋아요 API

src/main/java/com/das/das_backend/domain/user/domain/User.java, src/main/java/com/das/das_backend/domain/user/presentation/UserController.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/request/UpdateUserInfoRequest.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/response/QueryMyInfoResponse.java, src/main/java/com/das/das_backend/domain/user/service/UpdateUserInfoService.java
=> 🔀 :: (#83) MyPage 수정 API 추가

src/main/java/com/das/das_backend/domain/teacher/presentation/TeacherController.java, src/main/java/com/das/das_backend/domain/teacher/presentation/dto/request/UpdateStudentInfoRequest.java, src/main/java/com/das/das_backend/domain/teacher/service/UpdateStudentInfoService.java, src/main/java/com/das/das_backend/domain/user/domain/User.java, src/main/java/com/das/das_backend/domain/user/domain/repository/UserRepository.java, src/main/java/com/das/das_backend/domain/user/presentation/UserController.java, src/main/java/com/das/das_backend/domain/user/service/ChangePasswordService.java, src/main/java/com/das/das_backend/global/security/SecurityConfig.java
=> 🔀 :: (#87) 학생 정보 수정해주기 API

src/main/java/com/das/das_backend/domain/comment/service/CreateCommentService.java, src/main/java/com/das/das_backend/domain/user/domain/User.java, src/main/java/com/das/das_backend/domain/user/service/UserSignUpService.java
=> 🔀 :: (#89) 유저를 조회한 수 컬럼 추가

src/main/java/com/das/das_backend/domain/user/domain/User.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/request/UserSignUpRequest.java, src/main/java/com/das/das_backend/domain/user/service/UserSignUpService.java, src/main/java/com/das/das_backend/global/enums/Major.java
=> 🔀 :: (#110) User 엔티티 컬럼 추가

Dockerfile
=> 🔀 :: (#107) Dockerfile 세팅

src/main/java/com/das/das_backend/domain/club/domain/Club.java, src/main/java/com/das/das_backend/domain/user/domain/User.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/request/UserSignUpRequest.java, src/main/java/com/das/das_backend/domain/user/service/UserSignUpService.java, src/main/resources/application.yml
=> 🔀 :: (#114) 회원가입 로직 수정

.github/CODEOWNERS, src/main/java/com/das/das_backend/domain/feed/domain/Feed.java, src/main/java/com/das/das_backend/domain/feed/presentation/dto/request/CreateFeedRequest.java, src/main/java/com/das/das_backend/domain/feed/service/CreateFeedService.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/response/QueryMyInfoResponse.java, src/main/java/com/das/das_backend/domain/user/service/QueryMyInfoService.java
=> 🔀 :: (#119) 모집글 작성 API 수정

src/main/java/com/das/das_backend/domain/club/domain/Club.java, src/main/java/com/das/das_backend/domain/club/domain/repository/ClubRepository.java, src/main/java/com/das/das_backend/domain/club/exception/ClubNotFoundException.java, src/main/java/com/das/das_backend/domain/club/facade/ClubFacade.java, src/main/java/com/das/das_backend/domain/feed/domain/Feed.java, src/main/java/com/das/das_backend/domain/feed/presentation/dto/response/QueryFeedDetailResponse.java, src/main/java/com/das/das_backend/domain/feed/presentation/dto/response/QueryFeedListResponse.java, src/main/java/com/das/das_backend/domain/feed/service/CreateFeedService.java, src/main/java/com/das/das_backend/domain/feed/service/QueryFeedDetailService.java, src/main/java/com/das/das_backend/domain/feed/service/QueryFeedListService.java, src/main/java/com/das/das_backend/domain/feed/service/QueryFeedListViewsService.java, src/main/java/com/das/das_backend/domain/like/domain/Like.java, src/main/java/com/das/das_backend/domain/like/domain/repository/LikeRepository.java, src/main/java/com/das/das_backend/domain/like/facade/LikeFacade.java, src/main/java/com/das/das_backend/domain/like/service/LikeService.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java
=> 🔀 :: (#121) 좋아요 연관관계 수정

src/main/java/com/das/das_backend/domain/feed/domain/Feed.java, src/main/java/com/das/das_backend/domain/feed/presentation/dto/request/UpdateFeedRequest.java, src/main/java/com/das/das_backend/domain/feed/service/UpdateFeedService.java
=> 🔀 :: (#123) 모집글 수정 API 변경

src/main/java/com/das/das_backend/domain/user/domain/repository/UserRepository.java, src/main/java/com/das/das_backend/domain/user/presentation/UserController.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/response/QueryUserListResponse.java, src/main/java/com/das/das_backend/domain/user/service/QueryUserListService.java
=> 🔀 :: (#127) 유저 리스트 전체 조회 추가

src/main/java/com/das/das_backend/domain/user/domain/User.java, src/main/java/com/das/das_backend/domain/user/domain/types/LinkInfo.java
=> 🔀 :: (#131) 링크 추가

src/main/java/com/das/das_backend/domain/user/service/TokenRefreshService.java
=> 🔀 :: (#139) 리프레시토큰 버그 수정

src/main/java/com/das/das_backend/domain/notice/domain/repository/NoticeRepository.java, src/main/java/com/das/das_backend/domain/notice/presentation/NoticeController.java, src/main/java/com/das/das_backend/domain/notice/presentation/dto/response/QueryNoticeListResponse.java, src/main/java/com/das/das_backend/domain/notice/service/QueryNoticeListService.java
=> 🔀 :: (#137) 공지리스트 조회 API

src/main/java/com/das/das_backend/domain/user/service/TokenRefreshService.java, src/main/java/com/das/das_backend/global/security/SecurityConfig.java, src/main/resources/application.yml
=> 🔀 :: (#141) 값 추가, 이미지 권한 설

.github/workflows/CD.yml, Dockerfile, build.gradle
=> 🔀 :: (#143) CD 오류 수정

src/main/java/com/das/das_backend/domain/club/domain/Club.java, src/main/java/com/das/das_backend/domain/club/domain/repository/ClubRepository.java, src/main/java/com/das/das_backend/domain/club/exception/ClubAlreadyExistsException.java, src/main/java/com/das/das_backend/domain/club/facade/ClubFacade.java, src/main/java/com/das/das_backend/domain/club/presentation/ClubController.java, src/main/java/com/das/das_backend/domain/club/presentation/dto/request/CreateClubRequest.java, src/main/java/com/das/das_backend/domain/club/service/CreateClubService.java, src/main/java/com/das/das_backend/domain/user/presentation/dto/response/QueryUserListResponse.java, src/main/java/com/das/das_backend/domain/user/service/QueryUserListService.java, src/main/java/com/das/das_backend/global/error/ErrorCode.java
=> 🔀 :: (#147) 동아리 생성 API  

src/main/java/com/das/das_backend/domain/feed/presentation/dto/response/QueryFeedDetailResponse.java, src/main/java/com/das/das_backend/domain/feed/service/QueryFeedDetailService.java
=> 🔀 :: (#149) isMine 추가

src/main/java/com/das/das_backend/domain/club/domain/Club.java, src/main/java/com/das/das_backend/domain/club/presentation/ClubController.java, src/main/java/com/das/das_backend/domain/club/presentation/dto/request/UpdateClubRequest.java, src/main/java/com/das/das_backend/domain/club/service/UpdateClubService.java
=> 🔀 :: (#145) Club 수정 추가

src/main/java/com/das/das_backend/domain/club/presentation/ClubController.java, src/main/java/com/das/das_backend/domain/club/service/DeleteClubService.java
=> 🔀 :: (#146) Club 삭제 추가

src/main/java/com/das/das_backend/domain/club/domain/repository/ClubRepository.java, src/main/java/com/das/das_backend/domain/club/presentation/ClubController.java, src/main/java/com/das/das_backend/domain/club/presentation/dto/response/QueryClubElement.java, src/main/java/com/das/das_backend/domain/club/presentation/dto/response/QueryClubListResponse.java, src/main/java/com/das/das_backend/domain/club/service/QueryClubListService.java
=> 🔀 :: (#153) 동아리 리스트 전체 조회 api
